openapi: 3.0.0
info:
  title: ODD API
  description: |-
    A Web API for ODD (TEI or MEI) information.
    WARNING: the current version is considered alpha software.
    We welcome your feedback as well as bug reports and issues at 
    <https://github.com/Edirom/odd-api/issues>.
  version: 2.0.0-alpha
  license:
    name: AGPL-3.0 license
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  contact:
    name: ODD API Team
    url: https://github.com/Edirom/odd-api/
servers:
  - url: https://odd-api.edirom.de/v2
    description: Official ODD-API Server
  - url: http://localhost:8080/v2
    description: Local ODD-API development server
paths:
  /schemas:
    $ref: paths/schemas.yaml
  /{schema}:
    $ref: paths/{schema}.yaml
  /{schema}/{version}:
    $ref: paths/{schema}_{version}.yaml
 # /{schema}/{version}/attributes: #really?
 #   $ref: paths/{schema}_{version}_attributes.yaml
  /{schema}/{version}/classes:
    $ref: paths/{schema}_{version}_classes.yaml
  /{schema}/{version}/datatypes:
    $ref: paths/{schema}_{version}_datatypes.yaml
  /{schema}/{version}/elements:
    $ref: paths/{schema}_{version}_elements.yaml
  /{schema}/{version}/elements/{id}:
    $ref: paths/{schema}_{version}_elements_{id}.yaml
  /{schema}/{version}/macros:
    $ref: paths/{schema}_{version}_macros.yaml
  /{schema}/{version}/modules:
    $ref: paths/{schema}_{version}_modules.yaml
